// <auto-generated />
using System;
using AssignMate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssignMate.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260811093653_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AssignMate.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        ;

                    b.Property<int>("AccessFailedCount")
                        ;

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        ;

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        ;

                    b.Property<bool>("EmailConfirmed")
                        ;

                    b.Property<string>("FullName")
                        .IsRequired()
                        ;

                    b.Property<bool>("LockoutEnabled")
                        ;

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        ;

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("PasswordHash")
                        ;

                    b.Property<string>("PhoneNumber")
                        ;

                    b.Property<bool>("PhoneNumberConfirmed")
                        ;

                    b.Property<string>("Program")
                        .IsRequired()
                        ;

                    b.Property<string>("SecurityStamp")
                        ;

                    b.Property<string>("Semester")
                        .IsRequired()
                        ;

                    b.Property<bool>("TwoFactorEnabled")
                        ;

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AssignMate.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<DateTime>("CreatedAtUtc")
                        ;

                    b.Property<DateTime>("DueDate")
                        ;

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        ;

                    b.Property<int>("Priority")
                        ;

                    b.Property<int>("Status")
                        ;

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<DateTime>("UpdatedAtUtc")
                        ;

                    b.Property<string>("UserId")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DueDate");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        ;

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        ;

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("ClaimType")
                        ;

                    b.Property<string>("ClaimValue")
                        ;

                    b.Property<string>("RoleId")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("ClaimType")
                        ;

                    b.Property<string>("ClaimValue")
                        ;

                    b.Property<string>("UserId")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        ;

                    b.Property<string>("ProviderKey")
                        ;

                    b.Property<string>("ProviderDisplayName")
                        ;

                    b.Property<string>("UserId")
                        .IsRequired()
                        ;

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        ;

                    b.Property<string>("RoleId")
                        ;

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        ;

                    b.Property<string>("LoginProvider")
                        ;

                    b.Property<string>("Name")
                        ;

                    b.Property<string>("Value")
                        ;

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AssignMate.Models.TaskItem", b =>
                {
                    b.HasOne("AssignMate.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AssignMate.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AssignMate.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssignMate.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AssignMate.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}

